### ISSUE TITLE
Should we have the API have a static homepage?

### ISSUE THREAD

**Issue by hcpss-mbarger** [HCPSS/api.hcpss.org#5]
Currently the site does not output an index.html at the site root so any visitor accidentally stumbling upon the domain will receive a 403 error.

Should we put up a brief homepage blurb stating what the site is and have a link to contact information (particularly the webmaster@hcpss.org email)?

**Comment by hcpss-banderson** [comment]
I think if we put up an index page, then we have some responsibility to maintain it. I'm all for that, but we might want to talk about versioning the api first so that if we make big changes we don't break anyone's application using it.

I was also thinking we might want to have "BOE Cluster" and "Administrative Cluster" information up before launching.

**Comment by hcpss-mbarger** [comment]
Good points. I was actually only thinking about a simple header and email contact at this time.  More "webmaster etiquette" and less "API announcement and usage guidelines."

Similar to

```html
<h1>HCPSS Content API</h1>
<p>This site is a private API used by the Howard County Public School System. For site issues, please contact the <a href="mailto:webmaster@hcpss.org">site administrators</a>.</p>
```

**Comment by hcpss-banderson** [comment]
Ah ok. Sounds good.
